# name: Sync develop with master

# on:
#   push:
#     branches:
#       - master

# jobs:
#   sync-develop:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write
#       issues: write
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#           ref: develop
          
#       - name: Configure Git
#         run: |
#           git config user.name "GitHub Actions"
#           git config user.email "actions@github.com"
          
#       - name: Merge master into develop
#         run: |
#           git fetch origin master:master
#           git merge --no-ff origin/master -m "chore: Merge master into develop branch"
          
#       - name: Push changes
#         run: |
#           if ! git push origin develop; then
#             echo "Failed to push to develop branch"
#             exit 1
#           fi
        
#       - name: Handle Failure
#         if: failure()
#         uses: actions/github-script@v7
#         with:
#           script: |
#             const issueBody = `Automatic merge from master to develop failed.

#             Please resolve this manually

#             Workflow run: ${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`;
            
#             await github.rest.issues.create({
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               title: '🔄 Automatic master to develop merge failed',
#               body: issueBody,
#               labels: ['merge-failed', 'automation']
#             });
